name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - x86
        node:
          - 8
          - 10
          - 12
          - 14
          - 16
        os:
          - macOS-13
          - ubuntu-20.04
          - windows-2022
        exclude:
          - arch: x86
            os: macOS-13
          - arch: x86
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm test
      - run:
          echo ::set-output name=job_id::$(node -e
          "console.log(crypto.randomBytes(16).toString('hex'))")
        id: get_job_id
        shell: bash
